### ISSUE TITLE
Make list of clubs/leaders to interview.

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#30] opened 2015-07-14 06:44 UTC
One of the things not mentioned in our https://github.com/hackedu/hackedu/blob/71508adc8c092b2c1059cfa88b04537197a54635/meta/labs_program/meetings/15-07-13_initial_brainstorm.md discussion, but that we'll need to do is actually selecting the 12 clubs to partake in our labs program going into next semester. Any thoughts on selection criteria?

Also, for those who aren't familiar with our labs program, some initial detail is in those meeting notes.

/cc @jonleung

**Comment by jonleung** [comment] 2015-08-04 20:43
@zachlatta thoughts on "If you deviate from any of our curriculum, we want you to write up what you did so that others can reproduce it. Think a scientist who records his findings so that other people can reproduce it".

**Comment by zachlatta** [comment] 2015-08-04 20:49
What if we just push for not deviating from curriculum? At least for this
cohort.

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment] 2015-08-04 20:49
I feel like that'll help us better diagnose issues and work with the
leaders.

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment] 2015-08-05 03:27
@zachlatta Is there a reason your comments are cut off like that?

**Comment by zachlatta** [comment] 2015-08-05 03:45
I think it's just because I'm replying from my email and GitHub is hiding
my signature.

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment] 2015-08-05 04:59
Do you have an 80 character word-wrap on your emails?

**Comment by zachlatta** [comment] 2015-08-05 05:06
Most email clients wrap at 72 characters. See 3.0 in
http://www.ietf.org/rfc/rfc2646.txt.

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment] 2015-08-05 05:07
I should clarify: most email clients I know of wrap at 72 characters.

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment] 2015-08-05 05:32
Did you recently change something? I don't recall your old email comments doing this on github.

**Comment by zachlatta** [comment] 2015-08-05 06:14
Not that I know of. I believe my old ones did it too.

Hmm... odd.

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment] 2015-08-07 10:49
@zachlatta, what are your planned steps for this?

**Comment by zachlatta** [comment] 2015-08-07 10:52
Yeah, so I've started talking to a couple clubs when onboarding mentioning
that we will be doing this labs program and letting them know we'll get
back to them about whether we accept them.

My current plan is to have a personal planning document for putting this
together, at least until I have a better understanding of what the labs
program will look like.

On Fri, Aug 7, 2015 at 3:49 AM, Jonathan Leung <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta>, what are your planned steps
> for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/30#issuecomment-128671348>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment] 2015-08-10 17:52
@zachlatta, I just wanted to follow up on the email that you were going to draft to invite clubs to the labs program with the specific languaging of something like "We want you to come experiment and discover what works" as opposed to "We will help you".

**Comment by jonleung** [comment] 2015-08-12 23:23
As discussed, @zachlatta will add the first 12 names of clubs that he already came up with.

@zachlatta should ping me after he adds this list.

Every applicant in this list needs to have an associated "code name" that is like a heroku server generated name.

See this letter for potential phrasing: https://gist.github.com/jonleung/f5760ba7876adb07fd35

**Comment by zachlatta** [comment] 2015-08-18 17:38
Alright, we're tracking this over in https://docs.google.com/spreadsheets/d/1Q6E36NK7N_mKp_LJwMW-P3KUZXPsHQTJWyoyKvrneuc/edit#gid=0.

**Comment by MaxWofford** [comment] 2015-08-18 18:19
Closing this because @zachlatta posted the deliverable.

**Comment by zachlatta** [comment] 2015-08-18 18:28
Reopening because I'd like the deliverable to be in the GitHub repo. Creating a PR now...

**Comment by zachlatta** [comment] 2015-08-18 19:13
This is blocking on #49.

**Comment by zachlatta** [comment] 2015-08-18 19:57
Alright, so as discussed in today's standups we'll be proceeding with our existing pipeline + 3 clubs that @jonleung is going to add to the spreadsheet. Currently blocking on him doing that.

**Comment by jonleung** [comment] 2015-08-20 02:58
@zachlatta @hellyeah, I've added students listed below to the spreadsheet.

_Note that I've used abbreviations for their names_

- L.F
- G.Z.
- E.S.'s successor, J.R

**Comment by zachlatta** [comment] 2015-08-20 06:09
Awesome! Thanks.

This is just waiting on #57 to be merged now.

**Closed** 2015-08-20 22:38 UTC
Labels: blocking, labs
