### ISSUE TITLE
Create a list of people that we are going to invite to the labs Program

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#37] opened 2015-08-12 06:36 UTC
As discussed, @zachlatta will add the first 12 names of clubs that he already came up with.

@zachlatta should ping me after he adds this list.

Every applicant in this list needs to have an associated "code name" that is like a heroku server generated name.

See this letter for potential phrasing: https://gist.github.com/jonleung/f5760ba7876adb07fd35

**Comment by zachlatta** [comment] 2015-08-12 20:42
Duplicate of #30.

**Closed by zachlatta** 2015-08-12 20:42 UTC
