### ISSUE TITLE
Hack The North Meetup

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#217] opened 2015-09-17 15:57 UTC
I'm making a last-minute trip to Hack The North at Waterloo after getting my passport yesterday.

@paked and @JevinSidhu will be there? 

I should talk to them about heading it and have @jonleung @ssun098 and @LabLayers share notes.

**Comment by hellyeah** [comment] 2015-09-17 15:59
hackEDU/HS Hackers Meetups should eventually happen with no impetus from us.

HS Hackers Meetup Playbook?

**Comment by ssun098** [comment] 2015-09-17 18:00
@hellyeah this would be really, really helpful.  Do you want @LabLayers and me to help out with this?

**Comment by JevinSidhu** [comment] 2015-09-18 13:21
@hellyeah I'll be there!

**Comment by paked** [comment] 2015-09-18 13:42
I will be there :)

**Comment by hellyeah** [comment] 2015-09-18 16:18
@paked and @JevinSidhu do yall want to coordinate this meetup? 

Just got the ok from Kartik Talwar at HTN to do an impromptu meetup.

What do yall think of doing early in the day on Saturday?

**Comment by LabLayers** [comment] 2015-09-18 16:23
Hey everyone! Let's make a HS Hackers meetup happen! :dancer: Would love to chat on Fb in ~3 hours.

**Comment by paked** [comment] 2015-09-18 16:48
@dfont I'm cool to help coordinate if needed...

@lablayers keep me in the loop.

**Comment by JevinSidhu** [comment] 2015-09-18 17:48
@hellyeah I'd definitely be down to help out

@LabLayers Add me up: https://www.facebook.com/jevin.sidhu :smile:

**Comment by paked** [comment] 2015-09-19 06:41
@LabLayers @JevinSidhu @hellyeah is this happening?

**Comment by paked** [comment] 2015-09-19 13:42
OK. So for future reference, this is happening in https://www.facebook.com/events/996095017114040/996105970446278/

So far the link has been spread by

* HtN Slack
* Twitter (Shared using #hackthenorth, although I don't have a cult twitter following)
* Various facebook groups
  * HS Hackers (unconfirmed, perhaps not updated /cc: @JevinSidhu)
  * Hack the North (I made the event as part of that group, most people should have seen a notification... @JevinSidhu may have posted, so that should be checked out)
* HtN has a mobile app, maybe @hellyeah could get the the organisers to send out a push notification (not quite sure if this is worth it)

**Comment by LabLayers** [comment] 2015-09-19 21:40
Sounds awesome! :+1:

**Comment by paked** [comment] 2015-09-19 22:49
Closing because this is finished. Good job @JevinSidhu @hellyeah <3

**Closed by paked** 2015-09-19 22:49 UTC

**Comment by zachlatta** [comment] 2015-09-21 16:09
Any pictures from this meetup?

On Sat, Sep 19, 2015 at 3:49 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> Closing because this is finished. Good job @JevinSidhu
> <https://github.com/JevinSidhu> @hellyeah <https://github.com/hellyeah> <3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/217#issuecomment-141712288>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by ssun098** [comment] 2015-09-22 18:21
We should really establish that pictures need to be taken at meetups.
