### ISSUE TITLE
Create issues for every Labs Leader

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#142] opened 2015-09-01 16:14 UTC

**Comment by jonleung** [comment] 2015-09-01 17:04
@hellyeah, should this issue be in the private Labs repo (https://github.com/hackedu/labs-private)

**Comment by jonleung** [comment] 2015-09-01 17:05
Wait, @hellyeah, are these duplicates (https://github.com/hackedu/hackedu/issues/141)?

**Comment by jonleung** [comment] 2015-09-03 15:24
@hellyeah, poke ^

**Comment by zachlatta** [comment] 2015-09-03 15:38
Duplicate of #141.

**Closed by zachlatta** 2015-09-03 15:38 UTC
Labels: duplicate
